### PR TITLE
ability to provide custom headers AGJS-300

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AGJS-300

### CODE REVIEW

**Comment by lfryc** [comment]
@lholmquist I still have to test it - hmm reminds me that I should provide some tests :-)

**Comment by lfryc** [comment]
but be my guest if you want to review it yet, hehe

**Comment by lholmquist** [comment]
i'll be waiting patiently for those tests  :)


also,  can you add the options to the readme and the js-doc comments  :)

**Comment by lfryc** [comment]
@lholmquist sure thing, updates to come

**Comment by lfryc** [comment]
@lholmquist done, :eyes: :rainbow: :cat: ?

**Comment by lholmquist** [comment]
@lfryc looks good,  i'll merge then cut a release,  0.9.0

**Pull request merged**
