### PR TITLE
[RFC] - Update Message Format for the 1.1.X UPS series - AGPUSH-1318

### PR DESCRIPTION
**Pull request by lholmquist**
This updates to the new message format, https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/jaxrs/src/main/java/org/jboss/aerogear/unifiedpush/rest/sender/PushNotificationSenderEndpoint.java#L56-L93

@sebastienblanc @edewit mind taking a look

Also,  @edewit i wasn't sure what the descriptions for the windows stuff should be,  you can either PR against this one , or just tell me what they are and i can add them

### CODE REVIEW

**Comment by lholmquist** [comment]
rebased with latest changes

**Comment by edewit** [comment]
:+1:

**Comment by matzew** [comment]
should we update the example.js, to show bit a more of the new API ? instead of just that simple, flat message ?

**Comment by lholmquist** [comment]
@matzew that is probably a good idea,  let me add it

**Pull request merged**
