### PR TITLE
Agpush 1621 promises

### PR DESCRIPTION
**Pull request by lholmquist**
This is pretty much a total rewrite of the sender.

More to come,  just getting travis setup

### CODE REVIEW

**Comment by sebastienblanc** [comment]
Looks good :) Does it need a minimum version of Node ? (asking for a friend)

**Comment by lholmquist** [comment]
@sebastienblanc i believe the minimum is 4 for this.  because of the Arrow Functions and WeakMap, 

looks like i have travis testing on 5, i will change this to be 4.

i'm adding the old tests back in,  so lets no merge until those are in too

**Comment by lholmquist** [comment]
@sebastienblanc @matzew i think this is ready to go.  

i think once we merge this, we should probably do a 0.13.0 release.  then i can blog about it, then perhaps we do a 1.0.0 .  I feel like i want these changes to "sink in" with devs first, before going straight to a 1.0.0 since there have been major changes

**Comment by matzew** [comment]
👍

**Comment by lholmquist** [comment]
@matzew coolio, i'll probably merge later today, and get a release out

**Pull request merged**
